"""
Sample fusion menu for the AI recommendation engine.

This is PLACEHOLDER data built around the fusion combos your survey respondents
were most excited about (Japanese-Peruvian, Indian-Mexican, Levantine-Italian,
Emirati-French, Korean-Middle Eastern, Mediterranean-Latin American).

Replace this list with your real menu once it's finalized. Keep the same field
names ('id', 'name', 'category', ...) so the AI engine keeps working without
any code changes elsewhere.

Fields:
- spice_level: 0 (none) to 3 (very spicy)
- dietary: list of tags this dish satisfies -> "vegetarian", "vegan",
  "gluten_free", "no_pork", "no_alcohol", "contains_nuts", "contains_shellfish"
- cuisine_fusion: short label shown to guests, also used by the AI to match taste
"""

MENU = [
    {
        "id": "SP01",
        "name": "Wagyu Nikkei Tacos",
        "category": "Small Plates",
        "cuisine_fusion": "Japanese-Peruvian",
        "description": "Torched wagyu, tiger's milk aioli, crispy nori taco shell, pickled shallot.",
        "price_aed": 78,
        "spice_level": 1,
        "dietary": [],
        "signature": True,
    },
    {
        "id": "SP02",
        "name": "Manakish Margherita Flatbread",
        "category": "Small Plates",
        "cuisine_fusion": "Levantine-Italian",
        "description": "Za'atar-dusted dough, confit tomato, buffalo mozzarella, basil oil.",
        "price_aed": 52,
        "spice_level": 0,
        "dietary": ["vegetarian"],
        "signature": False,
    },
    {
        "id": "SP03",
        "name": "Korean Fried Kibbeh",
        "category": "Small Plates",
        "cuisine_fusion": "Korean-Middle Eastern",
        "description": "Bulgur & lamb kibbeh, gochujang glaze, pickled daikon, sesame.",
        "price_aed": 64,
        "spice_level": 2,
        "dietary": ["no_alcohol"],
        "signature": True,
    },
    {
        "id": "SP04",
        "name": "Truffle Hummus Croquettes",
        "category": "Small Plates",
        "cuisine_fusion": "Levantine-French",
        "description": "Crisp-fried chickpea croquettes, black truffle, tahini beurre blanc.",
        "price_aed": 58,
        "spice_level": 0,
        "dietary": ["vegetarian"],
        "signature": False,
    },
    {
        "id": "MC01",
        "name": "Tandoori Birria Tacos",
        "category": "Mains",
        "cuisine_fusion": "Indian-Mexican",
        "description": "Slow-braised lamb shoulder in tandoori-birria consomme, corn tortillas, mint-coriander salsa.",
        "price_aed": 115,
        "spice_level": 2,
        "dietary": [],
        "signature": True,
    },
    {
        "id": "MC02",
        "name": "Emirati Duck Confit",
        "category": "Mains",
        "cuisine_fusion": "Emirati-French",
        "description": "Duck leg confit, date-tamarind jus, saffron pomme puree, crispy shallots.",
        "price_aed": 145,
        "spice_level": 0,
        "dietary": ["gluten_free"],
        "signature": True,
    },
    {
        "id": "MC03",
        "name": "Peruvian Grilled Hammour",
        "category": "Mains",
        "cuisine_fusion": "Japanese-Peruvian",
        "description": "Charcoal-grilled local hammour, aji amarillo, yuzu-kosho butter, charred corn.",
        "price_aed": 135,
        "spice_level": 1,
        "dietary": ["gluten_free"],
        "signature": False,
    },
    {
        "id": "MC04",
        "name": "Shawarma-Spiced Ribeye",
        "category": "Mains",
        "cuisine_fusion": "Levantine-Latin American",
        "description": "Shawarma-rubbed ribeye, chimichurri, garlic toum, smoked eggplant.",
        "price_aed": 165,
        "spice_level": 1,
        "dietary": ["gluten_free"],
        "signature": True,
    },
    {
        "id": "MC05",
        "name": "Karak Butter Chicken",
        "category": "Mains",
        "cuisine_fusion": "Indian-Emirati",
        "description": "Butter chicken simmered in karak-spiced tomato cream, saffron rice, buttered naan.",
        "price_aed": 98,
        "spice_level": 2,
        "dietary": [],
        "signature": False,
    },
    {
        "id": "MC06",
        "name": "Wild Mushroom Risotto Manakish",
        "category": "Mains",
        "cuisine_fusion": "Italian-Levantine",
        "description": "Truffled wild mushroom risotto baked into a manakish crust, aged parmesan, thyme.",
        "price_aed": 92,
        "spice_level": 0,
        "dietary": ["vegetarian"],
        "signature": False,
    },
    {
        "id": "MC07",
        "name": "Miso-Harissa Black Cod",
        "category": "Mains",
        "cuisine_fusion": "Japanese-Levantine",
        "description": "Miso-harissa glazed black cod, charred baby leeks, sesame-tahini drizzle.",
        "price_aed": 158,
        "spice_level": 2,
        "dietary": ["gluten_free"],
        "signature": True,
    },
    {
        "id": "MC08",
        "name": "Jackfruit Al Pastor Curry",
        "category": "Mains",
        "cuisine_fusion": "Mexican-Indian",
        "description": "Pineapple al pastor-spiced jackfruit curry, coconut rice, pickled onion.",
        "price_aed": 78,
        "spice_level": 2,
        "dietary": ["vegan", "gluten_free"],
        "signature": False,
    },
    {
        "id": "DS01",
        "name": "Umm Ali Tres Leches",
        "category": "Desserts",
        "cuisine_fusion": "Emirati-Latin American",
        "description": "Emirati umm ali soaked tres-leches style, toasted pistachio, cinnamon cream.",
        "price_aed": 48,
        "spice_level": 0,
        "dietary": ["vegetarian"],
        "signature": True,
    },
    {
        "id": "DS02",
        "name": "Matcha Kunafa",
        "category": "Desserts",
        "cuisine_fusion": "Japanese-Levantine",
        "description": "Crisp kunafa pastry, matcha custard, white chocolate, pistachio dust.",
        "price_aed": 52,
        "spice_level": 0,
        "dietary": ["vegetarian", "contains_nuts"],
        "signature": True,
    },
    {
        "id": "DS03",
        "name": "Tahini Dulce de Leche Tart",
        "category": "Desserts",
        "cuisine_fusion": "Levantine-Latin American",
        "description": "Toasted tahini tart, dulce de leche, sea salt, dark chocolate shavings.",
        "price_aed": 46,
        "spice_level": 0,
        "dietary": ["vegetarian"],
        "signature": False,
    },
    {
        "id": "BV01",
        "name": "Saffron Pisco Sour (Mocktail)",
        "category": "Beverages",
        "cuisine_fusion": "Emirati-Peruvian",
        "description": "Non-alcoholic pisco-style sour, saffron syrup, lime, rose water foam.",
        "price_aed": 42,
        "spice_level": 0,
        "dietary": ["no_alcohol", "vegan"],
        "signature": False,
    },
    {
        "id": "BV02",
        "name": "Karak Old Fashioned (Mocktail)",
        "category": "Beverages",
        "cuisine_fusion": "Emirati-American",
        "description": "Karak tea reduction, date syrup, orange bitters, smoked ice.",
        "price_aed": 42,
        "spice_level": 0,
        "dietary": ["no_alcohol", "vegan"],
        "signature": True,
    },
]
